### ISSUE TITLE
Not an issue - Video Filters

### ISSUE THREAD

**Issue by WB2024** [fiso64/slsk-batchdl#59]
Thsi is not an issue but not sure how else to request this. is it possible to upload a version that filters to the isvideofile instead of the isaudiofile? so we can use it for downloading video?

**Comment by fiso64** [comment]
It's possible but you'd have to build it yourself. The easiest (although definitely not the proper) way of doing this is simply replacing `musicExtensions` with `videoExtensions` in the following two locations
https://github.com/fiso64/slsk-batchdl/blob/e74dc4beda4947fafdfa39cbab2b68c11b95b76e/slsk-batchdl/Utilities/Utils.cs#L14
https://github.com/fiso64/slsk-batchdl/blob/e74dc4beda4947fafdfa39cbab2b68c11b95b76e/slsk-batchdl/Utilities/Utils.cs#L19

Then just build it yourself using publish.bat or publish.sh

**Comment by fiso64** [comment]
Out of curiosity, why do you want that? Are there many video files being shared on Soulseek?

**Comment by fiso64** [comment]
I think the proper way to implement it would be to make it so that it doesn't check against a static array of audio extensions, but rather that it's set as a default in the required conditions. This would allow the user to specify the sets of file types that they want to consider with the `--format` argument.

But again, I've never heard of anyone using soulseek for anything that isn't music downloading, so I'm not sure if it's worth the effort.

**Comment by fiso64** [comment]
I've modified it so that the formats are stored in `--format` in the latest commit.
