### ISSUE TITLE
Feature Request - Download Specific File in Album

### ISSUE THREAD

**Issue by WB2024** [fiso64/slsk-batchdl#60]
Would it be possible to choose a specific file within an album/folder? 

so when you do a --album --interactive search it lists all the files in the folder/album but if you accept it downloads the entire folder, is it possible to request an option to download a specific file from within the folder? perhaps use index numbers for the file listings and enter the corresponding index number into the terminal to download the specific file? 

Thanks so much! 

love your application

**Comment by WB2024** [comment]
Or failing this, make file downloads interactive - so currently as i understand the --interactive option is not valid when searching for individual files, only when searching for albums/folders. if you could make it so file/track searches are interactive also this shoudl sever the same purpose.

**Comment by fiso64** [comment]
I can add that, although I'm not sure when I can get to that. Should be a simple change here
https://github.com/fiso64/slsk-batchdl/blob/cdf0813e6722a723fc5099374ea37687c2b04529/slsk-batchdl/Program.cs#L869
to make it return a list of one or multiple tracks rather than just the index of the selected album list, and to add controls to download individual items (e.g `sel:1` to download the first file, or `sel:1,2,3` to download multiple)

**Comment by WB2024** [comment]
Okay I've implemented this change! wasn't quite as simple but got there in the end. I can post the revision of program.cs somewhere if you like?

**Comment by fiso64** [comment]
Nice! just open a pull request, I'll check it out

**Comment by WB2024** [comment]
ive forked it and updated the file, coulndt work out how to do a pull request, the updated prgram.cs file is at 

https://github.com/WB2024/slsk-batchdl/blob/master/slsk-batchdl/Program.cs

**Comment by fiso64** [comment]
Seems like it's more complicated than it needs to be.. I'll do it

**Comment by fiso64** [comment]
Latest commit implements it 9dab77950afb0fa06486873642b19d2246d06533
