### ISSUE TITLE
Meaning of last 3 fields in _index.sldl is not described in documentation

### ISSUE THREAD

**Issue by MXC1** [fiso64/slsk-batchdl#69]
Apologies as this is not really an 'issue', but I don't know where else to ask.

-----

I'm trying to parse the _index.sldl files, but can't figure out what the last 3 columns for each track mean.
e.g. for this track, I'm trying to ascertain the meaning of `0,3,0`:
`E:\Music\sldl\tracks_and_playlists\Cobrah - BRAND NEW BITCH.mp3,COBRAH,BRAND NEW BITCH,BRAND NEW BITCH,196,0,3,0;`

I gather the second value (`3` in this example) is the State according to the last run. So:
1 = Downloaded
2 = Failed
3 = Exists
4 = NotFoundLastTime

But what do the other two mean?

-----

On a semi-related note, why use a custom format for the .sldl files? Why not just use a CSV? It would be much easier to parse.

-----

PS thanks for the software. It's a dream.

**Comment by fiso64** [comment]
Here's the format:
https://github.com/fiso64/slsk-batchdl/blob/85b94de64160097d9f375c402c9db5ccad4fe016/slsk-batchdl/M3uEditor.cs#L264-L266
and you can find the relevant enums [here](https://github.com/fiso64/slsk-batchdl/blob/master/slsk-batchdl/Enums.cs)

>On a semi-related note, why use a custom format for the .sldl files? Why not just use a CSV? It would be much easier to parse.

It's kind of silly, there's no particular reason.

**Comment by fiso64** [comment]
Ah, now I remember. There was a reason after all. It's basically just a csv which uses semicolons instead of line breaks, because in an earlier version the index waa stored in the same file as the m3u playlist lines, and storing it in a single line made the rest of the file more readable. But there is no reason for it anymore.

**Comment by fiso64** [comment]
for the next version, the index files will be in standard csv format (old ones will be converted)

**Comment by delpetra** [comment]
Please could I double check the right csv format for the index.sldl file? It looks like it is the Macintosh variant - if I edit the file and save as any other csv I get an "input string was not in correct format" when I try to reference it as my index file. (This is after updating to 2.4.0 and running the tool once to 'convert' my old .sldl file)

Using Excel to save as a Macintosh csv is readable by sldl but then the contents seem to get overwritten based on the subsequent run. Editing the file in notepad for Windows seems to work without this issue.

Reason I ask is because I am trying to edit the file to 'teach' it about other songs rather than relying solely on --skip-music-dir and filenames. (we discussed this briefly [here](https://github.com/fiso64/slsk-batchdl/issues/51).)

**Comment by fiso64** [comment]
Could you send one of these csv 'incorrect format' csv files here? I'll take a look

**Comment by delpetra** [comment]
Sure thing. I have appended .csv to both of the filenames so that I can upload them here.

- [library test - edited.sldl.csv](https://github.com/user-attachments/files/18571584/library.test.-.edited.sldl.csv) is a file I have manually edited in Excel to add the second track, then saved as a Macintosh csv
- [library test - rebuilt.sldl.csv](https://github.com/user-attachments/files/18571585/library.test.-.rebuilt.sldl.csv) is the output from sldl when I fed it 'edited' as the index file, i.e. it has rebuilt it from scratch

The command I used is as follows:

`sldl "C:\Users\Dan\OneDrive\Music\DJ\Utilities\slsk-batchdl\csv\2025-01-27 - WAP.csv" --user X --pass Y --pref-format mp3 --pref-min-bitrate 319 --pref-max-bitrate 321 --pref-max-samplerate 48000 --pref-strict-title true --pref-strict-album true --pref-accept-no-length false --input-type csv   --name-format "{sartist(/)salbum(/)sartist( - )stitle|sartist(/)salbum(/)filename}" --write-playlist --index-path "C:\Users\Dan\OneDrive\Music\DJ\Utilities\slsk-batchdl\test\library test.sldl" --skip-music-dir "C:\Users\Dan\OneDrive\Music" 
`

I can't immediately seem to recreate the "input string" issue above; I think I might have messed something up unknowingly when I was editing the file in Excel. Now it seems to work, regardless of what csv format I save as. I'll let you know if I face the issue again!
